### ISSUE TITLE
ie8 不支持ie8

### ISSUE THREAD

**Issue by tonn2y** [glaciall/jsBitmap#1]
在使用这个类库转换flash出来的argb数据时，生成的图片裂掉

**Comment by glaciall** [comment]
抱歉，之前没有在IE浏览器下做过测试，经测试发现，在FF和Chrome下正常的图片，在IE8下也不正常，另外，通过document.createElement('IMG')创建出来的元素，在IE系列浏览器上，会直接显示为红叉，必须通过new Image创建，很是神奇，而且即使是显示出来了，也存在不小的问题。

本项目本是弄着玩的东西，要真正实用的话，你可以找其它的jsbitmap的库，最好的是使用canvas标签来绘图，在IE8下，你可以尝试一下下面这篇文章。

http://blog.csdn.net/huang100qi/article/details/7698647

**Comment by tonn2y** [comment]
好的，我再寻找其他解决方案
